apiVersion: v1
kind: PersistentVolume
metadata:
  name: sastcontroller-pv
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: sastcontroller-pvc
  hostPath:
    path: "/pv/sastcontroller"
    type: DirectoryOrCreate
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sastcontroller-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  accessModes:
  - ReadWriteOnce
  volumeName: sastcontroller-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sastcontroller
spec:
  serviceName: sastcontroller
  replicas: 1
  selector:
    matchLabels:
      app: sastcontroller
  template:
    metadata:
      labels:
        app: sastcontroller
    spec:
      containers:
      - name: sastcontroller
        image: 'localhost:32000/sastcontroller'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: sastcontroller
          mountPath: /pv
        - name: sastctrlsecrets
          mountPath: /sastctrlsecrets        
        lifecycle:
          postStart:
            exec:
              command: ['cp', '/sastctrlsecrets/config.properties', '/usr/local/tomcat/webapps/scancentral-ctrl/WEB-INF/classes/']
      volumes:
        - name: sastcontroller
          persistentVolumeClaim:
            claimName: sastcontroller-pvc
        - name: sastctrlsecrets
          secret:
            secretName: sastctrlsecrets
      nodeSelector:
        kubernetes.io/hostname: ubuntu01
---
apiVersion: v1
kind: Service
metadata:
  name: sastcontroller
spec:
  selector:
    app: sastcontroller
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP
  clusterIP: 10.96.96.5
