DROP DATABASE IF EXISTS [ssc]
GO 
CREATE DATABASE [ssc] COLLATE SQL_Latin1_General_CP1_CS_AS;
GO
ALTER DATABASE [ssc] SET ANSI_NULL_DEFAULT ON 
ALTER DATABASE [ssc] SET AUTO_UPDATE_STATISTICS_ASYNC ON
ALTER DATABASE [ssc] SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE [ssc] SET READ_COMMITTED_SNAPSHOT ON 
GO
USE [ssc]
GO
:r ../prereq/create-tables.sql
