apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssc-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: ssc-pvc    
  hostPath:
    path: "/pv/fortify"
    type: DirectoryOrCreate
    
    
