apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexusiq-work-pv
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: nexusiq-work-pvc
  hostPath:
    path: "/pv/nexusiq/work"
    type: DirectoryOrCreate
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexusiq-work-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  accessModes:
  - ReadWriteOnce
  volumeName: nexusiq-work-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexusiq-log-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: nexusiq-log-pvc
  hostPath:
    path: "/pv/nexusiq/log"
    type: DirectoryOrCreate
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexusiq-log-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  volumeName: nexusiq-log-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexusiq
spec:
  serviceName: nexusiq
  replicas: 1
  selector:
    matchLabels:
      app: nexusiq
  template:
    metadata:
      labels:
        app: nexusiq
    spec:
      securityContext:
        runAsUser: 0      
      containers:
        - name: nexusiq
          command: ["/usr/bin/java"]
          args: ["-jar", "/opt/sonatype/nexus-iq-server/nexus-iq-server-1.106.0-01.jar", "server", "/nexusiqsecrets/config.yml"]
          ports:
            - name: https-web
              containerPort: 8443
              protocol: TCP        
            - name: https-web-mon
              containerPort: 8444
              protocol: TCP        
          image: sonatype/nexus-iq-server
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nexusiqwork
              mountPath: /sonatype-work
            - name: nexusiqlog
              mountPath: /var/log/nexus-iq-server      
            - name: nexusiqsecrets
              mountPath: /nexusiqsecrets                
      volumes:
        - name: nexusiqwork
          persistentVolumeClaim:
            claimName: nexusiq-work-pvc
        - name: nexusiqlog
          persistentVolumeClaim:
            claimName: nexusiq-log-pvc
        - name: nexusiqsecrets
          secret:
            secretName: nexusiqsecrets        
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/hostname: ubuntu01
---
apiVersion: v1
kind: Service
metadata:
  name: nexusiq
spec:
  selector:
    app: nexusiq
  ports:
    - name: https-web
      protocol: TCP
      port: 443
      targetPort: 8443
    - name: https-web-mon
      protocol: TCP
      port: 444
      targetPort: 8444
  type: ClusterIP
  clusterIP: 10.96.96.7
